{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Error Handling\n",
    "==============\n",
    "\n",
    "Exceptions\n",
    "----------\n",
    "\n",
    "Here’s a sample data used for our previous lab (press `Ctrl+Enter` to\n",
    "create a text file, `accounts.txt`):"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%writefile accounts.txt\n",
    "1|2000|0.1\n",
    "2|1000.12 | 0.1\n",
    "3|3500.4|0.25"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Here’s a sample solution for our previous lab (press `Ctrl + Enter` to\n",
    "run the code):"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_monthly_interest(account_balance, annual_rate):\n",
    "    monthly_rate = float(annual_rate) / 12\n",
    "    return monthly_rate * float(account_balance)\n",
    "\n",
    "def print_accounts(acct_file):\n",
    "    with open(acct_file, \"r\") as f:\n",
    "        print('Id    Interest')\n",
    "        for line in f:\n",
    "            id, balance, rate = line.strip().split('|')\n",
    "            print(f'{id:6s}{calculate_monthly_interest(float(balance), float(rate)):.3f}')\n",
    "\n",
    "\n",
    "print_accounts(\"accounts.txt\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In an ideal world, when an input file has no missing field, invalid\n",
    "data, or other issues, this solution would work as expected. However in\n",
    "reality, there are some common errors from an input file which can cause\n",
    "exceptions. If these exceptions are not handled properly our program\n",
    "would crash unexpectedly.\n",
    "\n",
    "**(Try it)** What will happen to our program when given this input file?\n",
    "Can you interpret the error message displayed to you?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%%writefile accounts.txt\n",
    "1 |2000|0.1\n",
    "2|1000.12 | 0.1\n",
    "3|3500.4|0.25\n",
    "4|2005|"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run the cell above to regenerate accounts.txt first and then run this cell\n",
    "print_accounts(\"accounts.txt\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "The program will crash with a\n",
    "`ValueError: could not convert string to float`, because the last field\n",
    "(annual rate) is missing from the last line and Python cannot convert an\n",
    "empty `string` to a `float`.\n",
    "\n",
    "</details>\n",
    "\n",
    "**(Try it)** What exceptions will be generated by the following errors?\n",
    "\n",
    "1.  A file is not found\n",
    "2.  A name not found in local or global scope\n",
    "3.  A function is applied to an object of incorrect type\n",
    "4.  A function gets argument of correct type but improper value.\n",
    "\n",
    "<details>\n",
    "\n",
    "<summary><b>Answers</b></summary>\n",
    "\n",
    "1.  A file is not found: `FileNotFoundError`\n",
    "2.  A name not found in local or global scope: `UnboundLocalError`\n",
    "3.  A function is applied to an object of incorrect type: `TypeError`\n",
    "4.  A function gets argument of correct type but improper value:\n",
    "    `ValueError`\n",
    "\n",
    "</details>\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "Handling Exceptions\n",
    "-------------------\n",
    "\n",
    "**(Try it)**\n",
    "\n",
    "-   Update the input file to create some invalid lines (lines with\n",
    "    missing or extra fields, with strings not been able to be converted\n",
    "    to floats, etc.) to test your programs.\n",
    "\n",
    "Python’s exception objects contain more information than just the error\n",
    "type. In order to access the information, we can assign the object to a\n",
    "variable that we can use inside the `except` clause:\n",
    "\n",
    "``` python\n",
    "except Exception as err:\n",
    "    # log err, the exception object\n",
    "    invalid_lines += 1\n",
    "```\n",
    "\n",
    "**(Try it)** If you print the exception object, what will you see?\n",
    "\n",
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "A message similar to those we can see when our programs have crashed.\n",
    "\n",
    "</details>\n",
    "\n",
    "The following code works as expected if an input file can be opened\n",
    "successfully."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_monthly_interest(account_balance, annual_rate):\n",
    "    if (account_balance<=0) or (annual_rate) <= 0:\n",
    "        raise ValueError(\"A positive number is expected\")\n",
    "    monthly_rate = float(annual_rate) / 12\n",
    "    return monthly_rate * float(account_balance)\n",
    "\n",
    "def print_accounts(acct_file):\n",
    "    with open(acct_file, \"r\") as f:\n",
    "        invalid_lines = 0\n",
    "        print('Id    Interest')\n",
    "        for line in f:\n",
    "            try:\n",
    "                id, balance, rate = line.strip().split('|')\n",
    "                print(f'{id:6s}{calculate_monthly_interest(float(balance), float(rate)):.3f}')\n",
    "            except:\n",
    "                invalid_lines += 1\n",
    "\n",
    "        if invalid_lines > 0:\n",
    "            print(f'Warning: Invalid lines ({invalid_lines}) found in the input file')\n",
    "\n",
    "print_accounts(\"accounts.txt\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**(Try it)** What will happen if we change the file name to\n",
    "`accounts_non_existent.txt` or `open(acct_file, \"r\")` to\n",
    "`open(acct_file, \"a\")`?\n",
    "\n",
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "Our program would crash and Python would print a Traceback (a list which\n",
    "shows the path that the exception has raised through, all the way back\n",
    "to the original line which caused the error) and some error message.\n",
    "\n",
    "</details>\n",
    "\n",
    "**(Try it)** If you do not want exceptions raised by errors from opening\n",
    "a file to terminate your program, how would you update your code?\n",
    "\n",
    "<details>\n",
    "\n",
    "<summary><b>Sample solution</b></summary>\n",
    "\n",
    "You can enclose the `with` block in a `try-except` block:\n",
    "\n",
    "``` python\n",
    "def print_accounts(acct_file):\n",
    "    invalid_lines = 0\n",
    "    try:\n",
    "        with open(acct_file, \"r\") as f: \n",
    "            ...\n",
    "    except:\n",
    "        ...\n",
    "```\n",
    "\n",
    "</details>\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "**(Try it)** Rewrite the following to print `Bye` and finish if the user\n",
    "enters non-numeric input:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "while True:\n",
    "    number = input(\"Enter a number: \")\n",
    "    print(\"Your number squared is\", int(number)**2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Answer**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run this cell (Shift+Enter) to see the answer\n",
    "\n",
    "%load /examples/intro/4_error_handling/handle_error.py"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**(Try it)** What will be printed when `foo()` is called?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def foo():\n",
    "    try:\n",
    "        x = 1/1\n",
    "    except:\n",
    "        print(\"exception\")\n",
    "        raise\n",
    "    else:\n",
    "        print(\"else\")\n",
    "    finally:\n",
    "        print(\"finally\")\n",
    "\n",
    "    print(x)\n",
    "\n",
    "foo()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "``` shell\n",
    "  else\n",
    "  finally\n",
    "  1.0\n",
    "```\n",
    "\n",
    "</details>\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "**(Try it)** What will be printed when `foo()` is called?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def foo():\n",
    "    try:\n",
    "        x = 1/0\n",
    "    except ZeroDivisionError:\n",
    "        print(\"divide by zero\")\n",
    "        raise\n",
    "    except:\n",
    "        print(\"exception\")\n",
    "        raise\n",
    "    else:\n",
    "        print(\"else\")\n",
    "    finally:\n",
    "        print(\"finally\")\n",
    "\n",
    "    print(x)\n",
    "\n",
    "foo()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "    divide by zero\n",
    "    finally\n",
    "    ---------------------------------------------------------------------------\n",
    "    ZeroDivisionError                         Traceback (most recent call last)\n",
    "    ......\n",
    "\n",
    "    ZeroDivisionError: division by zero\n",
    "\n",
    "</details>\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "**(Try it)** What will be printed when `foo()` is called?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def foo():\n",
    "    try:\n",
    "        x = 1/0\n",
    "    except:\n",
    "        print(\"exception\")\n",
    "        raise\n",
    "    else:\n",
    "        print(\"else\")\n",
    "    finally:\n",
    "        print(\"finally\")\n",
    "\n",
    "    print(x)\n",
    "\n",
    "foo()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "    exception\n",
    "    finally\n",
    "    ---------------------------------------------------------------------------\n",
    "    ZeroDivisionError                         Traceback (most recent call last)\n",
    "    ......\n",
    "\n",
    "    ZeroDivisionError: division by zero\n",
    "\n",
    "</details>\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "**(Try it)** What will be printed when `foo()` is called?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def foo():\n",
    "    try:\n",
    "        x = 1/0\n",
    "    except Exception as e:\n",
    "        print(e)\n",
    "        raise\n",
    "    else:\n",
    "        print(\"else\")\n",
    "    finally:\n",
    "        print(\"finally\")\n",
    "\n",
    "    print(x)\n",
    "\n",
    "\n",
    "foo()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "    division by zero\n",
    "    finally\n",
    "    ---------------------------------------------------------------------------\n",
    "    ZeroDivisionError                         Traceback (most recent call last)\n",
    "    ......\n",
    "\n",
    "    ZeroDivisionError: division by zero\n",
    "\n",
    "</details>\n",
    "\n",
    "------------------------------------------------------------------------\n",
    "\n",
    "**(Try it)** What will happen when `foo()` is called?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def foo():\n",
    "    try:\n",
    "        x = 1/0\n",
    "    except Exception as e:\n",
    "        print(e)\n",
    "    else:\n",
    "        print(\"else\")\n",
    "    finally:\n",
    "        print(\"finally\")\n",
    "\n",
    "    print(x)\n",
    "\n",
    "foo()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<details>\n",
    "\n",
    "<summary><b>Answer</b></summary>\n",
    "\n",
    "    division by zero\n",
    "    finally\n",
    "    ---------------------------------------------------------------------------\n",
    "    UnboundLocalError                         Traceback (most recent call last)\n",
    "    ......\n",
    "\n",
    "    UnboundLocalError: local variable 'x' referenced before assignment\n",
    "\n",
    "-   After an error message is printed, the normal control flow is\n",
    "    resumed in the `except` clause.\n",
    "-   The next statement to be executed is `print(x)` but\n",
    "-   `x` is not created due to the exception caused by `x = 1/0`.\n",
    "    Therefore we will get a `UnboundLocalError` at this point.\n",
    "\n",
    "🧰 Takeaway: **[Errors should never pass\n",
    "silently](https://www.python.org/dev/peps/pep-0020/)**\n",
    "\n",
    "</details>"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
